# Navigation Links
#   To link a homepage section, use a hash `#` followed by the section ID.
#   The weight parameter defines the order that the links appear.

main:
  - name: Education
    url: /#experience
    weight: 10
  - name: Papers
    url: /#blog
    weight: 20
  - name: Internships
    url: /#projects
    weight: 30
  - name: Tech Stack
    url: /#skills
    weight: 40
  - name: Contact
    url: /#contact
    weight: 50
